extern void init(void);
extern int initializeAll(void);
extern void initializeData(void);
extern void start(void);
extern int ctrlTask(struct params *motor);
extern void control(struct params *motor);
extern void torqCtrl(void);
extern void Nop(void);
extern void getCurrentStatus(void);
extern void getCurrentPosition(void);
extern void CurCtrl(struct params *param);
extern void DirCtrl(struct params *param, int trig);
extern void Inv(void);
extern void output(double volt[], double torq[]);
extern void fin(void);
extern int logsTask(void);
extern int logSave(double buff[]);
extern void logw(void);
extern void logWrite(void);
extern void logsoff(void);
extern void out(double rv, double lv);
extern void VelCtrl(struct params *param, int trig);
extern void velocities(double vel[]);
extern void vel(double vel_r, double vel_l);
extern void velocities(double velo[]);
extern void velwomega(double velo, double ome);
extern void velome(double velo, double rev_radius);
extern void TraCtrl(struct params *param, int trig);
extern void trace(double velo);
extern void tra(double velo);
extern void tra2(double veloc, double rad);
extern void trace2(double veloc, double radius);
extern void TraCtrl2(struct params *param, int trig);
extern void Pre(void);
extern void tra3(double velo, double rad);
extern void trace3(double velo, double radius);
extern void TraCtrl3(struct params *param, int trig);
extern void tra4(double velo);
extern void trace4(double velo);
extern void TraCtrl4(struct params *param, int trig);
extern void tra4_L1(void);
extern void tra4_L2(void);
extern void tra5(double velo);
extern void trace5(double velo);
extern void TraCtrl5(struct params *param, int trig);
extern void Tra5_L1(void);
extern void Tra5_L2(void);
extern void Tra5_L3(void);
extern void Tra5_L4(void);
extern void Tra5_L5(void);
extern void TraCtrl6(struct params *param, int trig);
extern void Tra6_L1(void);
extern void Tra6_L2(void);
extern void Tra6_L3(void);
extern void Tra6_L4(void);
extern void Tra6_L5(void);
extern void getCurrentControlPosition(void);
extern void tra6(double velo);
extern void trace6(double velo);
extern void TraCtrl5_alpha(void);
extern void TorqCtrl(void);
extern void ModelCtrl2(struct params *param, int trig);
extern void ModelCtrl3(struct params *param, int trig);
extern void ModelCtrl3a(struct params *param, int trig);
extern void Mod3a_L1(void);
extern void Mod3a_L2(void);
extern void Mod3a_L3(void);
extern void Mod3a_L4(void);
extern void Mod3a_L5(void);
extern void ModelCtrl4(struct params *param, int trig);
extern void ModelCtrl5(struct params *param, int trig);
extern void Mod5_L1(void);
extern void Mod5_L2(void);
extern void Mod5_L3(void);
extern void Mod5_L4(void);
extern void Mod5_L5(void);
extern void RepulsiveForce(void);
extern void getNearestDistance(void);
extern void AvoidCtrl1(struct params *param, int trig);
extern void AvoidCtrl2(struct params *param, int trig);
extern void AvoidCtrl3(struct params *param, int trig);
extern void AvoidCtrl4(struct params *param, int trig);
extern void AvoidCtrl5(struct params *param, int trig);
extern void ModelCtrlOnly(struct params *param, int trig);
extern void ModelCtrlOnly2(struct params *param, int trig);
extern void avo1(double dam0, double dam1);
extern void avo2(double dam0, double dam1);
extern void avo3(double dam0, double dam1);
extern void avo4(double dam0, double dam1);
extern void mod2(double velo, double dam0, double dam1, double mas, double ine);
extern void AD_test(struct params *param, int trig);
extern void ADCtrl(void);
extern void SlopeCtrl(struct params *param, int trig);
extern void adtest(void);
extern void slope(double dam0, double dam1);
extern void lms(double dam0, double dam1);
extern void demo(double dam0, double dam1);
extern void obs(double dam0, double dam1);
extern void get_sick_data(void);
extern void getObstacleAbsoluteCoordinate(void);
extern void LMSAvoidCtrl(struct params *param, int trig);
extern void DEMOAvoidCtrl(struct params *param, int trig);
extern void OBSCtrl(struct params *param, int trig);
extern void modcas(double dam0, double dam1);
extern void modmod(double dam0, double dam1);
extern void avo5(double dam0, double dam1);
extern void mod3(double dam0, double dam1);
extern void mod4(double dam0, double dam1);
extern void mod5(double dam0, double dam1);
extern void modonly(double dam0, double dam1);
